version: '3.5'


services:
  database:
    restart: 'always'
    container_name: 'database'
    image: 'postgres:14.5'
    ports:
      - 5432:5432
    env_file:
      - .env

  bot:
    restart: 'always'
    env_file:
      - .env.prod
    build: ./bot
    container_name: bot
    depends_on:
      - database